# Generated by Django 3.2.6 on 2021-08-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_id_todoitem_id1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='id1',
            new_name='id',
        ),
    ]
