# Generated by Django 3.2.6 on 2021-08-11 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_id1_todoitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
